language: python

python:
  - "2.7"

before_script:
  - mkdir -p vendors
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.10.zip -nv
  - unzip -qd vendors google_appengine_1.9.10.zip
  - mysql -e 'create database hat_dev;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('hatDev.14') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - python manage.py syncdb --noinput

install:
  - pip install -r requirements.txt
  - pip install mysql-python

script: python manage.py test --with-coverage

branches:
  only:
    - testing
