language: python

python:
  - "2.7"

before_script:
  - mkdir -p vendors
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.10.zip -nv
  - unzip -qd vendors google_appengine_1.9.10.zip

install:
  - pip install -r requirements.txt

script: nosetests

branches:
  only:
    - dev
