language: python

python:
  - "2.7"

env:
  - DJANGO_VERSION=1.5.8
  - DJANGO_VERSION=1.6.0
  - DJANGO_VERSION=1.7.0

install: "pip install -r requirements.txt"

script: nosetests

branches:
  only:
    - dev
