application: hatteron1
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- warmup

handlers:
- url: /favicon.ico
  static_files: /static/img/ico/favicon.ico
  upload: /static/img/ico/favicon.ico

- url: /templates
  static_dir: templates

- url: /static
  static_dir: static

libraries:
- name: django
  version: "1.5"

builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'hat.settings'
